import './components/Caja'
import './components/Cinema'
import './components/Modal'
import './components/ClientList'
import './components/CinemaContext'
import './components/Timer'
import './style.css'
